# SEE AN EXAMPLE AT https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/mods.toml

# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[34,)"
# The license for your mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="zlib License"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues"

[[mods]]
    modId="golems"
    version="11.3.1"
    displayName="Extra Golems"
    credits="TheGlitch76, jriwanek, AtelierAmber, and translators - Thanks!"
    authors="skyjay1 and the MMD Team"
    description='''Adds dozens of golems to the minecraft universe, each with unique textures and abilities!'''
    logoFile="golem_logo.png"
[[dependencies.golems]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.golems]]
    modId="quark"
    mandatory=false
    versionRange="[r2.4-307,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.golems]]
    modId="thermal"
    mandatory=false
    versionRange="[1.0.5,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.golems]]
    modId="clib"
    mandatory=false
    versionRange="[1.5.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.golems]]
    modId="mekanism"
    mandatory=false
    versionRange="[1.16.3-10.0.15.441,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.golems]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[1.16.3-4.1.1-127,)"
    ordering="AFTER"
    side="BOTH"
